"""add priority and updated_at to tickets

Revision ID: 557bb551d3ee
Revises: c1d94111540b
Create Date: 2026-06-01 16:21:50.085060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557bb551d3ee'
down_revision: Union[str, Sequence[str], None] = 'c1d94111540b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
